### ISSUE TITLE
How to run this code correctly

### ISSUE THREAD

**Issue by Hanjunzhe** [JyChen9811/DOC-VTON#3]
What is the meaning of recommending PF-VTON as a Codebase? Should PF-VTON code be combined with the code in it?
I directly downloaded the code here and ran it using the command. The error is as follows. How can I modify the code?

/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/scipy/sparse/_index.py:22: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  _bool_scalar_types = (bool, numpy.bool, numpy.bool_)
Traceback (most recent call last):
  File "/dataA/iedA/hjz/DOC-VTON-main/test_w_enhance.py", line 5, in <module>
    from models.afwm import AFWM
  File "/dataA/iedA/hjz/DOC-VTON-main/models/afwm.py", line 4, in <module>
    from .correlation import correlation
  File "/dataA/iedA/hjz/DOC-VTON-main/models/correlation/correlation.py", line 5, in <module>
    import cupy
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupy/__init__.py", line 46, in <module>
    import cupyx as _cupyx
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/__init__.py", line 8, in <module>
    from cupyx import linalg  # NOQA
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/linalg/__init__.py", line 2, in <module>
    from cupyx.linalg import sparse  # NOQA
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/linalg/sparse/__init__.py", line 3, in <module>
    from cupyx.linalg.sparse._solve import lschol  # NOQA
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/linalg/sparse/_solve.py", line 7, in <module>
    from cupyx.scipy import sparse
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/scipy/__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.base import spmatrix as _spmatrix
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/scipy/sparse/__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.coo import coo_matrix  # NOQA
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/scipy/sparse/coo.py", line 12, in <module>
    from cupyx.scipy.sparse import csc
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/scipy/sparse/csc.py", line 11, in <module>
    from cupyx.scipy.sparse import compressed
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/scipy/sparse/compressed.py", line 22, in <module>
    from cupyx.scipy.sparse import _index
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/cupyx/scipy/sparse/_index.py", line 22, in <module>
    _bool_scalar_types = (bool, numpy.bool, numpy.bool_)
  File "/dataA/iedA/anaconda3/envs/hjzVTON/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by Hanjunzhe** [comment]
@JyChen9811 May I ask if you could provide some suggestions

**Comment by JyChen9811** [comment]
Please check the conda environment correctly.
![image](https://github.com/JyChen9811/DOC-VTON/assets/68991221/89392f5e-6d39-4e3b-bb8e-b30180bd88df)
